---

dist: bionic

language: python
python:
  - 3.6
services: docker

env:
  global:
    - ROLE_NAME: terraform
  matrix:
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: fedora29

install:
  - pip install molecule docker flake8 ansible-lint

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
