---

- name: Converge
  hosts: all
  vars:
    version: '0.12.24'
  roles:
    - role: ansible-role-terraform
      vars:
        terraform_version: "{{ version }}"
        terraform_binary_dir_path: /usr/bin
        terraform_plugin_urls:
          - https://github.com/dmacvicar/terraform-provider-libvirt/releases/download/v0.6.11/terraform-provider-libvirt_0.6.11_linux_amd64.zip
