---

name: molecule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_default:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu2004
          - ubuntu1804
          # - centos7
          # - centos8
          - debian10
          - debian11
          - fedora35
          # - amazonlinux2
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: run molecule (default scenario)
        uses: robertdebock/molecule-action@4.0.7
        with:
          command: "test"
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}

  test_versioned:
    needs:
      - test_default
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu2004
          - ubuntu1804
          - centos7
          - centos8
          - debian10
          - debian11
          - fedora35
          - amazonlinux2
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: run molecule (versioned scenario)
        uses: robertdebock/molecule-action@4.0.7
        with:
          scenario: versioned
          command: "test"
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}

  deploy:
    needs:
      - test_default
      - test_versioned
    runs-on: ubuntu-latest
    steps:
      - name: to Ansible Galaxy
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.head_ref == 'master')
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
